project:
  type: website
  output-dir: docs
  
execute:
  freeze: true

website:
  title: "Пространственная статистика"
  page-footer: |
        © 2023, Тимофей Самсонов, Географический факультет МГУ имени М. В. Ломоносова
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

lang: ru

